//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUserManagement.web
{


    public partial class UserDetailsV2
    {

        /// <summary>
        /// NoteUserControlV2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DemoUserManagement.web.NoteUserControlV2 NoteUserControlV2;

        /// <summary>
        /// DocumentUserControlV2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DemoUserManagement.web.DocumentUserControlV2 DocumentUserControlV2;
    }
}
