//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUserManagement.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hobby
    {
        public int HobbyID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Hobbies { get; set; }
        public string Message { get; set; }
        public string Feedback { get; set; }
    
        public virtual StudentDetail StudentDetail { get; set; }
    }
}
