//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportFuelManagement.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelTransaction
    {
        public int TransactionID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int TransactionType { get; set; }
        public string AirportID { get; set; }
        public string AircraftID { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<int> TransactionIDParent { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual Airport Airport { get; set; }
    }
}
